name: Copper VM CI
on: [push, pull_request]

jobs:
  linux-build:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build programs
        run: ./scripts/build_programs.sh

      - name: Build examples
        run: ./scripts/build_examples.sh

      - name: Tests
        run: go test ./...
