name: Copper VM CI
on: [push, pull_request]

jobs:
  linux-build:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Build programs binaries
        run: python ./scripts/build.py

      - name: Compile examples
        run: python ./scripts/test.py com ./test/ && python ./scripts/test.py com ./examples/

      - name: Unit Tests
        run: go test ./...

      - name: Run tests
        run : python ./scripts/test.py run ./test/

      - name: Run examples
        run: python ./scripts/test.py run ./examples/
